### ISSUE TITLE
MacOS version support

### ISSUE THREAD

**Issue by chelaxian** [MatthewPierson/PyBoot#56]
Which MacOS version support PyBoot?
I am trying to get it on High Sierra 10.13.6 (hackintosh).
Should it work?

**Comment by chelaxian** [comment]
stuck on this

[MacBook-Air-chelaxian:PyBoot-master chelaxian$ sudo python3 pyboot.py  -i iPad4,4 11.4.1
PyBoot - A tool for tether booting Checkm8 vulnerable iOS devices by Matty, @mosk_i

Current version is: Beta 0.9.1
Make sure your device is connected in DFU mode
Checking theiphonewiki for 11.4.1 keys...
Found Keys!
Downloading 11.4.1's BuildManifest.plist
Extracting: BuildManifest.plist, from iPad_64bit_11.4.1_15G77_Restore.ipsw
Found multiple device models...
Which is your device?

1: j71ap
2: j72ap
3: j73ap
4: j85ap
5: j86ap
6: j87ap

Enter the number that corresponds with your device: 4
Device set to j85ap
Getting SHSH for signing images
Downloading and patching 11.4.1's iBSS/iBEC
Extracting: Firmware/dfu/iBEC.ipad4b.RELEASE.im4p, from iPad_64bit_11.4.1_15G77_Restore.ipsw
Extracting: Firmware/dfu/iBSS.ipad4b.RELEASE.im4p, from iPad_64bit_11.4.1_15G77_Restore.ipsw
dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/chelaxian/Downloads/PyBoot-master/./resources/bin/img4tool (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/chelaxian/Downloads/PyBoot-master/./resources/bin/img4tool
dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/chelaxian/Downloads/PyBoot-master/./resources/bin/img4tool (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/chelaxian/Downloads/PyBoot-master/./resources/bin/img4tool
dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/chelaxian/Downloads/PyBoot-master/./resources/bin/img4tool (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/chelaxian/Downloads/PyBoot-master/./resources/bin/img4tool
dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/chelaxian/Downloads/PyBoot-master/./resources/bin/img4tool (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/chelaxian/Downloads/PyBoot-master/./resources/bin/img4tool
dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/chelaxian/Downloads/PyBoot-master/./resources/bin/img4tool (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/chelaxian/Downloads/PyBoot-master/./resources/bin/img4tool
dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/chelaxian/Downloads/PyBoot-master/./resources/bin/img4tool (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/chelaxian/Downloads/PyBoot-master/./resources/bin/img4tool
dyld: Library not loaded: /usr/local/lib/libpng16.16.dylib
  Referenced from: /Users/chelaxian/Downloads/PyBoot-master/./resources/bin/ibootim
  Reason: image not found
dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/chelaxian/Downloads/PyBoot-master/./resources/bin/img4tool (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/chelaxian/Downloads/PyBoot-master/./resources/bin/img4tool
dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/chelaxian/Downloads/PyBoot-master/./resources/bin/img4tool (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/chelaxian/Downloads/PyBoot-master/./resources/bin/img4tool
Downloading 11.4.1's KernelCache
Extracting: kernelcache.release.ipad4b, from iPad_64bit_11.4.1_15G77_Restore.ipsw
Downloading 11.4.1's DeviceTree
Extracting: Firmware/all_flash/DeviceTree.j85ap.im4p, from iPad_64bit_11.4.1_15G77_Restore.ipsw
iOS version is 11.x, not downloading trustcache
Patching Kernel's type from krnl to rkrn
iOS version is 11.x, skipping trustcache patching
Patching Devicetree's type from dtre to rdtr
Signing boot files
dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/chelaxian/Downloads/PyBoot-master/./resources/bin/img4tool (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/chelaxian/Downloads/PyBoot-master/./resources/bin/img4tool
dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/chelaxian/Downloads/PyBoot-master/./resources/bin/img4tool (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/chelaxian/Downloads/PyBoot-master/./resources/bin/img4tool
dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/chelaxian/Downloads/PyBoot-master/./resources/bin/img4tool (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/chelaxian/Downloads/PyBoot-master/./resources/bin/img4tool
Exploiting device with checkm8

**Comment by danieltroger** [comment]
Compile img4tool then. I have it working on 10.13.6
